package vista;

import conexion.Conexion;
import controlador.VehiculoController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Vehiculo;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patmi
 */
public class FormMenu extends javax.swing.JFrame {

         private int idVehiculo = 0;

         /**
          * Creates new form FormMenu
          */
         public FormMenu() {
                  initComponents();
                  this.setSize(900, 550);
                  this.setLocationRelativeTo(null);
                  this.setResizable(false);
                  this.setTitle("Sistema Parcking Gecko");

                  //Cargar la tabla
                  this.CargarTablaVehiculos();
         }

         /**
          * This method is called from within the constructor to initialize the form. WARNING: Do
          * NOT modify this code. The content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings( "unchecked" )
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jPanel1 = new javax.swing.JPanel();
                  jLabel1 = new javax.swing.JLabel();
                  jLabel_logo = new javax.swing.JLabel();
                  jButton_cerrar_sesion = new javax.swing.JButton();
                  jPanel2 = new javax.swing.JPanel();
                  jTabbedPane1 = new javax.swing.JTabbedPane();
                  jPanel_registrar_vehiculo = new javax.swing.JPanel();
                  jLabel2 = new javax.swing.JLabel();
                  jLabel3 = new javax.swing.JLabel();
                  jLabel4 = new javax.swing.JLabel();
                  jLabel5 = new javax.swing.JLabel();
                  jTextField_placa = new javax.swing.JTextField();
                  jTextField_propietario = new javax.swing.JTextField();
                  jComboBox_tipo_vehiculo = new javax.swing.JComboBox<>();
                  jButton_registrar = new javax.swing.JButton();
                  jLabel6 = new javax.swing.JLabel();
                  jPanel_retirar_vehiculo = new javax.swing.JPanel();
                  jLabel10 = new javax.swing.JLabel();
                  jLabel_info = new javax.swing.JLabel();
                  jLabel11 = new javax.swing.JLabel();
                  jLabel12 = new javax.swing.JLabel();
                  jLabel13 = new javax.swing.JLabel();
                  jLabel14 = new javax.swing.JLabel();
                  jLabel15 = new javax.swing.JLabel();
                  jTextField_placa_retiro = new javax.swing.JTextField();
                  jButton_buscar_placa = new javax.swing.JButton();
                  jButton_retirar = new javax.swing.JButton();
                  jLabel_propietario = new javax.swing.JLabel();
                  jLabel_hora_entrada = new javax.swing.JLabel();
                  jLabel_hora_salida = new javax.swing.JLabel();
                  jLabel_valor_pagar = new javax.swing.JLabel();
                  jPanel_administrar_vehiculos = new javax.swing.JPanel();
                  jLabel7 = new javax.swing.JLabel();
                  jLabel8 = new javax.swing.JLabel();
                  jLabel9 = new javax.swing.JLabel();
                  jTextField_busqueda_criterio = new javax.swing.JTextField();
                  jDateChooser_fecha_busqueda = new com.toedter.calendar.JDateChooser();
                  jScrollPane1 = new javax.swing.JScrollPane();
                  jTable_vehiculos = new javax.swing.JTable();
                  jButton_buscar = new javax.swing.JButton();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jPanel1.setBackground(new java.awt.Color(204, 204, 255));
                  jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
                  jLabel1.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel1.setText("Sistema Parking Gecko");
                  jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 230, 30));

                  jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GeckoLogoPag2.png"))); // NOI18N
                  jLabel_logo.setText("jLabel2");
                  jPanel1.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 150, 150));

                  jButton_cerrar_sesion.setBackground(new java.awt.Color(0, 51, 102));
                  jButton_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jButton_cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
                  jButton_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
                  jButton_cerrar_sesion.setText("CERRAR SESION");
                  jButton_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton_cerrar_sesionActionPerformed(evt);
                           }
                  });
                  jPanel1.add(jButton_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 210, 45));

                  getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

                  jPanel2.setBackground(new java.awt.Color(0, 51, 102));
                  jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
                  jTabbedPane1.setForeground(new java.awt.Color(0, 51, 102));

                  jPanel_registrar_vehiculo.setBackground(new java.awt.Color(204, 204, 255));
                  jPanel_registrar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                  jLabel2.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel2.setText("Registro de Ingreso de Vehiculos al Parking");
                  jPanel_registrar_vehiculo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 500, -1));

                  jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jLabel3.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel3.setText("Placa:");
                  jPanel_registrar_vehiculo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

                  jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jLabel4.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel4.setText("Propietario:");
                  jPanel_registrar_vehiculo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 30));

                  jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jLabel5.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel5.setText("Tipo de Vehiculo:");
                  jPanel_registrar_vehiculo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 30));

                  jTextField_placa.setBackground(new java.awt.Color(255, 255, 255));
                  jTextField_placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jTextField_placa.setForeground(new java.awt.Color(0, 0, 0));
                  jTextField_placa.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyPressed(java.awt.event.KeyEvent evt) {
                                    jTextField_placaKeyPressed(evt);
                           }
                  });
                  jPanel_registrar_vehiculo.add(jTextField_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 230, 30));

                  jTextField_propietario.setBackground(new java.awt.Color(255, 255, 255));
                  jTextField_propietario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jTextField_propietario.setForeground(new java.awt.Color(0, 0, 0));
                  jPanel_registrar_vehiculo.add(jTextField_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 30));

                  jComboBox_tipo_vehiculo.setBackground(new java.awt.Color(255, 255, 255));
                  jComboBox_tipo_vehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jComboBox_tipo_vehiculo.setForeground(new java.awt.Color(0, 0, 0));
                  jComboBox_tipo_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Automóvil", "Motocicleta" }));
                  jPanel_registrar_vehiculo.add(jComboBox_tipo_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 230, 30));

                  jButton_registrar.setBackground(new java.awt.Color(0, 51, 102));
                  jButton_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jButton_registrar.setForeground(new java.awt.Color(255, 255, 255));
                  jButton_registrar.setText("REGISTRAR");
                  jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton_registrarActionPerformed(evt);
                           }
                  });
                  jPanel_registrar_vehiculo.add(jButton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, 40));

                  jLabel6.setBackground(new java.awt.Color(204, 204, 255));
                  jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coche-revisado.png"))); // NOI18N
                  jPanel_registrar_vehiculo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 100, 50));

                  jTabbedPane1.addTab("Registrar Vehiculo", jPanel_registrar_vehiculo);

                  jPanel_retirar_vehiculo.setBackground(new java.awt.Color(204, 204, 255));
                  jPanel_retirar_vehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                  jLabel10.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel10.setText("Retiro de Vehiculos del Parking");
                  jPanel_retirar_vehiculo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 360, -1));

                  jLabel_info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                  jLabel_info.setForeground(new java.awt.Color(153, 0, 0));
                  jLabel_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel_info.setText("Vehiculo Retirado");
                  jPanel_retirar_vehiculo.add(jLabel_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, 30));

                  jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel11.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel11.setText("Placa:");
                  jPanel_retirar_vehiculo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 30));

                  jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel12.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel12.setText("Propietario:");
                  jPanel_retirar_vehiculo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, 30));

                  jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel13.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel13.setText("Hora Entrada:");
                  jPanel_retirar_vehiculo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 30));

                  jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel14.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel14.setText("Hora Salida:");
                  jPanel_retirar_vehiculo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, 30));

                  jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel15.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel15.setText("Valor a Pagar:");
                  jPanel_retirar_vehiculo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 150, 30));

                  jTextField_placa_retiro.setBackground(new java.awt.Color(255, 255, 255));
                  jTextField_placa_retiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                  jTextField_placa_retiro.setForeground(new java.awt.Color(0, 0, 0));
                  jTextField_placa_retiro.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jTextField_placa_retiroActionPerformed(evt);
                           }
                  });
                  jPanel_retirar_vehiculo.add(jTextField_placa_retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, 30));

                  jButton_buscar_placa.setBackground(new java.awt.Color(0, 51, 102));
                  jButton_buscar_placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jButton_buscar_placa.setForeground(new java.awt.Color(255, 255, 255));
                  jButton_buscar_placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
                  jButton_buscar_placa.setText("BUSCAR");
                  jPanel_retirar_vehiculo.add(jButton_buscar_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, 30));

                  jButton_retirar.setBackground(new java.awt.Color(0, 51, 102));
                  jButton_retirar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jButton_retirar.setForeground(new java.awt.Color(255, 255, 255));
                  jButton_retirar.setText("RETIRAR");
                  jPanel_retirar_vehiculo.add(jButton_retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 300, 250, 30));

                  jLabel_propietario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel_propietario.setForeground(new java.awt.Color(0, 0, 0));
                  jLabel_propietario.setText("ALGUIEN");
                  jPanel_retirar_vehiculo.add(jLabel_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 30));

                  jLabel_hora_entrada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel_hora_entrada.setForeground(new java.awt.Color(0, 0, 0));
                  jLabel_hora_entrada.setText("00:00:00");
                  jPanel_retirar_vehiculo.add(jLabel_hora_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, 30));

                  jLabel_hora_salida.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel_hora_salida.setForeground(new java.awt.Color(0, 0, 0));
                  jLabel_hora_salida.setText("00:00:00");
                  jPanel_retirar_vehiculo.add(jLabel_hora_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 150, 30));

                  jLabel_valor_pagar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel_valor_pagar.setForeground(new java.awt.Color(0, 0, 0));
                  jLabel_valor_pagar.setText("$ 00.00");
                  jPanel_retirar_vehiculo.add(jLabel_valor_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 150, 30));

                  jTabbedPane1.addTab("Retirar Vehiculo", jPanel_retirar_vehiculo);

                  jPanel_administrar_vehiculos.setBackground(new java.awt.Color(204, 204, 255));
                  jPanel_administrar_vehiculos.setForeground(new java.awt.Color(255, 255, 255));
                  jPanel_administrar_vehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                  jLabel7.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel7.setText("Administración de Vehiculos del Parking");
                  jPanel_administrar_vehiculos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 30));

                  jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel8.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel8.setText("Placa/Propietario:");
                  jPanel_administrar_vehiculos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

                  jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                  jLabel9.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel9.setText("Fecha:");
                  jPanel_administrar_vehiculos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 30));

                  jTextField_busqueda_criterio.setBackground(new java.awt.Color(255, 255, 255));
                  jTextField_busqueda_criterio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jTextField_busqueda_criterio.setForeground(new java.awt.Color(0, 0, 0));
                  jPanel_administrar_vehiculos.add(jTextField_busqueda_criterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, 30));

                  jDateChooser_fecha_busqueda.setBackground(new java.awt.Color(255, 255, 255));
                  jDateChooser_fecha_busqueda.setForeground(new java.awt.Color(0, 0, 0));
                  jDateChooser_fecha_busqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jPanel_administrar_vehiculos.add(jDateChooser_fecha_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 150, 30));

                  jScrollPane1.setBackground(new java.awt.Color(0, 51, 102));
                  jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

                  jTable_vehiculos.setBackground(new java.awt.Color(255, 255, 255));
                  jTable_vehiculos.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  jScrollPane1.setViewportView(jTable_vehiculos);

                  jPanel_administrar_vehiculos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 580, 230));

                  jButton_buscar.setBackground(new java.awt.Color(0, 51, 102));
                  jButton_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
                  jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
                  jButton_buscar.setText("BUSCAR");
                  jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton_buscarActionPerformed(evt);
                           }
                  });
                  jPanel_administrar_vehiculos.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 130, 30));

                  jTabbedPane1.addTab("Administrar Vehiculos", jPanel_administrar_vehiculos);

                  jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 400));

                  getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 550));

                  pack();
         }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrar_sesionActionPerformed
             //System.exit(0);
             FormLogin log = new FormLogin();
             log.setVisible(true);
             this.dispose();
             System.out.println("CERRO SESIÓN");
    }//GEN-LAST:event_jButton_cerrar_sesionActionPerformed

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
             String placa = jTextField_placa.getText().trim();
             String propietario = jTextField_propietario.getText().trim();

             if ( placa.isEmpty() || propietario.isEmpty() ) {
                      JOptionPane.showMessageDialog(null, "Ingrese datos antes de registrar");
             } else {
                      //Validar selección del tipo de vehiculo
                      String tipo_vehiculo = jComboBox_tipo_vehiculo.getSelectedItem().toString().trim();
                      if ( tipo_vehiculo.equalsIgnoreCase("Seleccione:") ) {
                               JOptionPane.showMessageDialog(null, "Seleccione el tipo de vehiculo");
                      } else {
                               VehiculoController controlVehiculo = new VehiculoController();
                               Vehiculo vehiculo = new Vehiculo();

                               vehiculo.setPlaca(placa);
                               vehiculo.setPropietario(propietario);
                               vehiculo.setTipoVehiculo(tipo_vehiculo);

                               //Fecha y hora de entrada
                               DateFormat dateFormatFecha = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                               Calendar calendar = Calendar.getInstance();
                               Date date = calendar.getTime();
                               String fecha = dateFormatFecha.format(date);

                               vehiculo.setHoraEntrada(fecha);
                               vehiculo.setHoraSalida(null);
                               vehiculo.setEstado("INGRESADO");

                               if ( controlVehiculo.guardar(vehiculo) ) {
                                        JOptionPane.showMessageDialog(null, "*** Ingreso de Vehiculo Registrado ***");
                                        //Cargar la tabla de Vehiculos
                                        this.CargarTablaVehiculos();
                                        //-------------------------------

                                        //Limpiar campos
                                        jTextField_placa.setText("");
                                        jTextField_propietario.setText("");
                                        jComboBox_tipo_vehiculo.setSelectedItem("Seleccione:");
                               } else {
                                        JOptionPane.showMessageDialog(null, "Error al Registrar Ingreso de Vehiculo");
                               }
                      }
             }

    }//GEN-LAST:event_jButton_registrarActionPerformed

         private void jTextField_placaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_placaKeyPressed
                  if ( evt.getKeyCode() == evt.VK_ENTER ) {
                           jTextField_propietario.requestFocus();
                  }
         }//GEN-LAST:event_jTextField_placaKeyPressed

         private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
                  String PlacaPropietarioBusqueda = jTextField_busqueda_criterio.getText().trim();
                  Date fechaBusqueda = jDateChooser_fecha_busqueda.getDate();
                  String fechaComoCadena = "";

                  if ( fechaBusqueda != null ) {
                           SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                           fechaComoCadena = sdf.format(fechaBusqueda);
                  }

                  if ( PlacaPropietarioBusqueda.isEmpty() && fechaComoCadena.isEmpty() ) {
                           JOptionPane.showMessageDialog(null, "Ingrese Placa o Propietario para realizar la busqueda");
                           this.CargarTablaVehiculos();
                  } else {

                           VehiculoController vehiculoController = new VehiculoController();

                           vehiculoController.buscarVehiculosPlacaFecha(PlacaPropietarioBusqueda, fechaComoCadena);
                           ArrayList<Vehiculo> listaVehiculo = vehiculoController.listaVehiculo;

                           DefaultTableModel model = new DefaultTableModel();

                           this.jTable_vehiculos = new JTable(model);
                           this.jScrollPane1.setViewportView(this.jTable_vehiculos);
                           model.addColumn("N°"); //Id
                           model.addColumn("Placa");
                           model.addColumn("Propietario");
                           model.addColumn("Tipo de Vehiculo");
                           model.addColumn("Valor Pagado");
                           model.addColumn("Estado");

                           Object fila[] = new Object[ 6 ];
                           for ( Vehiculo vehiculo : listaVehiculo ) {
                                    fila[ 0 ] = vehiculo.getIdVehiculo();
                                    fila[ 1 ] = vehiculo.getPlaca();
                                    fila[ 2 ] = vehiculo.getPropietario();
                                    fila[ 3 ] = vehiculo.getTipoVehiculo();
                                    fila[ 4 ] = vehiculo.getValorPagado();
                                    fila[ 5 ] = vehiculo.getEstado();
                                    model.addRow(fila);
                           }

                           //Evento
                           jTable_vehiculos.addMouseListener(new MouseAdapter() {
                                    @Override
                                    public void mouseClicked( MouseEvent e ) {
                                             int fila_point = jTable_vehiculos.rowAtPoint(e.getPoint());
                                             int columna_point = 0;

                                             if ( fila_point > -1 ) {
                                                      idVehiculo = ( int ) model.getValueAt(fila_point, columna_point);
                                                      EnviarDatosVehiculoSeleccionado(idVehiculo); //Método
                                             }
                                    }
                           });
                  }

                  //Limpiar campo
                  jTextField_busqueda_criterio.setText("");

         }//GEN-LAST:event_jButton_buscarActionPerformed

         private void jTextField_placa_retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_placa_retiroActionPerformed
                  // TODO add your handling code here:
         }//GEN-LAST:event_jTextField_placa_retiroActionPerformed

         /**
          * @param args the command line arguments
          */
         public static void main( String args[] ) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                                    if ( "Nimbus".equals(info.getName()) ) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch ( ClassNotFoundException ex ) {
                           java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch ( InstantiationException ex ) {
                           java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch ( IllegalAccessException ex ) {
                           java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
                           java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new FormMenu().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JButton jButton_buscar;
         private javax.swing.JButton jButton_buscar_placa;
         private javax.swing.JButton jButton_cerrar_sesion;
         private javax.swing.JButton jButton_registrar;
         private javax.swing.JButton jButton_retirar;
         private javax.swing.JComboBox<String> jComboBox_tipo_vehiculo;
         private com.toedter.calendar.JDateChooser jDateChooser_fecha_busqueda;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel10;
         private javax.swing.JLabel jLabel11;
         private javax.swing.JLabel jLabel12;
         private javax.swing.JLabel jLabel13;
         private javax.swing.JLabel jLabel14;
         private javax.swing.JLabel jLabel15;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JLabel jLabel4;
         private javax.swing.JLabel jLabel5;
         private javax.swing.JLabel jLabel6;
         private javax.swing.JLabel jLabel7;
         private javax.swing.JLabel jLabel8;
         private javax.swing.JLabel jLabel9;
         private javax.swing.JLabel jLabel_hora_entrada;
         private javax.swing.JLabel jLabel_hora_salida;
         private javax.swing.JLabel jLabel_info;
         private javax.swing.JLabel jLabel_logo;
         private javax.swing.JLabel jLabel_propietario;
         private javax.swing.JLabel jLabel_valor_pagar;
         private javax.swing.JPanel jPanel1;
         private javax.swing.JPanel jPanel2;
         private javax.swing.JPanel jPanel_administrar_vehiculos;
         private javax.swing.JPanel jPanel_registrar_vehiculo;
         private javax.swing.JPanel jPanel_retirar_vehiculo;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JTabbedPane jTabbedPane1;
         private javax.swing.JTable jTable_vehiculos;
         private javax.swing.JTextField jTextField_busqueda_criterio;
         private javax.swing.JTextField jTextField_placa;
         private javax.swing.JTextField jTextField_placa_retiro;
         private javax.swing.JTextField jTextField_propietario;
         // End of variables declaration//GEN-END:variables

         //Método para mostrar todos los vehiculos en la tabla
         private void CargarTablaVehiculos() {
                  Connection cn = Conexion.conectar();
                  DefaultTableModel model = new DefaultTableModel();
                  String sql = "select id_vehiculo, placa, propietario, tipo_vehiculo, valor_pagado, estado from tb_vehiculo";
                  Statement st;
                  try {
                           st = cn.createStatement();
                           ResultSet rs = st.executeQuery(sql);
                           this.jTable_vehiculos = new JTable(model);
                           this.jScrollPane1.setViewportView(this.jTable_vehiculos);

                           model.addColumn("N°"); //Id
                           model.addColumn("Placa");
                           model.addColumn("Propietario");
                           model.addColumn("Tipo de Vehiculo");
                           model.addColumn("Valor Pagado");
                           model.addColumn("Estado");

                           while ( rs.next() ) {
                                    Object fila[] = new Object[ 6 ];
                                    for ( int i = 0; i < 6; i++ ) {
                                             fila[ i ] = rs.getObject(i + 1);
                                    }
                                    model.addRow(fila);
                           }

                  } catch ( SQLException e ) {
                           System.out.println("ERROR AL LLENAR LA TABLA DE VEHICULOS: " + e);
                  }

                  //Evento
                  jTable_vehiculos.addMouseListener(new MouseAdapter() {
                           @Override
                           public void mouseClicked( MouseEvent e ) {
                                    int fila_point = jTable_vehiculos.rowAtPoint(e.getPoint());
                                    int columna_point = 0;

                                    if ( fila_point > -1 ) {
                                             idVehiculo = ( int ) model.getValueAt(fila_point, columna_point);
                                             EnviarDatosVehiculoSeleccionado(idVehiculo); //Método
                                    }
                           }
                  });
         }

         //Método que envia datos seleccionados
         private void EnviarDatosVehiculoSeleccionado( int idVehiculo ) {
                  try {
                           Connection cn = Conexion.conectar();
                           PreparedStatement pst = cn.prepareStatement("select * from tb_vehiculo where id_vehiculo = '" + idVehiculo + "'");
                           ResultSet rs = pst.executeQuery();
                           if ( rs.next() ) {
                                    DetalleVehiculo detalle = new DetalleVehiculo();
                                    detalle.setVisible(true);

                                    DetalleVehiculo.jLabel_placa_detalle.setText(rs.getString("placa"));
                                    DetalleVehiculo.jLabel_propietario_detalle.setText(rs.getString("propietario"));
                                    DetalleVehiculo.jLabel_hora_entrada_detalle.setText(rs.getString("hora_entrada"));
                                    DetalleVehiculo.jLabel_hora_salida_detalle.setText(rs.getString("hora_salida"));
                                    DetalleVehiculo.jLabel_valor_pagado_detalle.setText(rs.getString("valor_pagado"));
                                    DetalleVehiculo.jLabel_tipo_vehiculo_detalle.setText(rs.getString("tipo_vehiculo"));
                                    DetalleVehiculo.jLabel_estado_detalle.setText(rs.getString("estado"));
                           }

                  } catch ( SQLException e ) {
                           System.out.println("ERROR AL SELECCIONAR EL VEHICULO: " + e);
                  }
         }

}
