/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.UsuarioController;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author patmi
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setTitle("Sistema Parcking Gecko");
        this.setSize(900, 550);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jPanel1 = new javax.swing.JPanel();
                  jLabel1 = new javax.swing.JLabel();
                  jLabel2 = new javax.swing.JLabel();
                  jLabel3 = new javax.swing.JLabel();
                  jTextField_usuario = new javax.swing.JTextField();
                  jPasswordField_password = new javax.swing.JPasswordField();
                  jButton_acceder = new javax.swing.JButton();
                  jLabel6 = new javax.swing.JLabel();
                  jPanel2 = new javax.swing.JPanel();
                  jLabel4 = new javax.swing.JLabel();
                  jLabel5 = new javax.swing.JLabel();
                  jLabel7 = new javax.swing.JLabel();
                  jLabel8 = new javax.swing.JLabel();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jPanel1.setBackground(new java.awt.Color(204, 204, 255));
                  jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                  jLabel1.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel1.setText("INICIAR SESIÓN");
                  jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 110, 240, -1));

                  jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jLabel2.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel2.setText("Usuario");
                  jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 60, 20));

                  jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jLabel3.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel3.setText("Password");
                  jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 240, 80, 20));

                  jTextField_usuario.setBackground(new java.awt.Color(255, 255, 255));
                  jTextField_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jTextField_usuario.setForeground(new java.awt.Color(0, 0, 0));
                  jTextField_usuario.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jTextField_usuarioActionPerformed(evt);
                           }
                  });
                  jTextField_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyPressed(java.awt.event.KeyEvent evt) {
                                    jTextField_usuarioKeyPressed(evt);
                           }
                  });
                  jPanel1.add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, 240, 30));

                  jPasswordField_password.setBackground(new java.awt.Color(255, 255, 255));
                  jPasswordField_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jPasswordField_password.setForeground(new java.awt.Color(0, 0, 0));
                  jPasswordField_password.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyPressed(java.awt.event.KeyEvent evt) {
                                    jPasswordField_passwordKeyPressed(evt);
                           }
                  });
                  jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 270, 240, 30));

                  jButton_acceder.setBackground(new java.awt.Color(0, 51, 102));
                  jButton_acceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                  jButton_acceder.setForeground(new java.awt.Color(255, 255, 255));
                  jButton_acceder.setText("ACCEDER");
                  jButton_acceder.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton_accederActionPerformed(evt);
                           }
                  });
                  jPanel1.add(jButton_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 320, 240, 40));

                  jLabel6.setForeground(new java.awt.Color(0, 51, 102));
                  jLabel6.setText("v.1.0");
                  jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                  getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 350, 550));

                  jPanel2.setBackground(new java.awt.Color(0, 51, 102));
                  jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                  jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                  jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel4.setText("Sistema de Parking Gecko");
                  jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, 460, -1));

                  jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                  jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                  jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubicacion.png"))); // NOI18N
                  jLabel5.setText("Av Abraham Lincoln, Residencial Puerta de Hierro, Monterrey, N.L.");
                  jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 400, -1));

                  jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                  jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                  jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono.png"))); // NOI18N
                  jLabel7.setText("+52 81 1167 5303");
                  jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 455, 400, -1));

                  jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GeckoLogo.png"))); // NOI18N
                  jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 250, 250));

                  getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

                  pack();
         }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuarioActionPerformed

    private void jButton_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accederActionPerformed
        //Llamada del método para que el boton realice la accion
        this.IniciarSesion();
    }//GEN-LAST:event_jButton_accederActionPerformed

         private void jTextField_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usuarioKeyPressed
                  if ( evt.getKeyCode() == evt.VK_ENTER ) {
                           jPasswordField_password.requestFocus();
                  }
         }//GEN-LAST:event_jTextField_usuarioKeyPressed

         private void jPasswordField_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwordKeyPressed
                  if ( evt.getKeyCode() == evt.VK_ENTER ) {
                           //jTextField_propietario.requestFocus();
                           this.IniciarSesion();
                  }
         }//GEN-LAST:event_jPasswordField_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JButton jButton_acceder;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JLabel jLabel4;
         private javax.swing.JLabel jLabel5;
         private javax.swing.JLabel jLabel6;
         private javax.swing.JLabel jLabel7;
         private javax.swing.JLabel jLabel8;
         private javax.swing.JPanel jPanel1;
         private javax.swing.JPanel jPanel2;
         private javax.swing.JPasswordField jPasswordField_password;
         private javax.swing.JTextField jTextField_usuario;
         // End of variables declaration//GEN-END:variables

    //Método para iniciar sesión
    private void IniciarSesion() {
        if (jTextField_usuario.getText().isEmpty() && jPasswordField_password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese su usuario y password");
        } else {
            UsuarioController controlUsuario = new UsuarioController();
            Usuario usuario = new Usuario();
            usuario.setUsuario(jTextField_usuario.getText().trim());
            usuario.setPass(jPasswordField_password.getText().trim());

            if (controlUsuario.login(usuario)) {
                System.out.println("INICIO SESIÓN CON EXITO");
                //JOptionPane.showMessageDialog(null, "INICIO SESIÓN CON EXITO");
                
                FormMenu menu= new FormMenu();
                menu.setVisible(true);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Password incorrecta");
            }
        }
    }

}
